#ifndef MACRO_H
#define MACRO_H

//OFFSET_VAL
#define PID_OFFSET_VAL 0x00
#define PCR_OFFSET_VAL 0x04
#define CFG_OFFSET_VAL 0x08
#define START_OFFSET_VAL 0x0C
#define RPT_OFFSET_VAL 0x10
#define PER_OFFSET_VAL 0x14
#define PH1D_OFFSET_VAL 0x18

//RESET_VAL
#define PID_RESET_VAL 0x42071100
#define PCR_RESET_VAL 0x00
#define CFG_RESET_VAL 0x00
#define START_RESET_VAL 0x00
#define RPT_RESET_VAL 0x00
#define PER_RESET_VAL 0x00
#define PH1D_RESET_VAL 0x00

//WRITE_WRITE_MASK
#define PID_WRITE_MASK_VAL 0x00
#define PCR_WRITE_MASK_VAL 0x01
#define CFG_WRITE_MASK_VAL 0x7F
#define START_WRITE_MASK_VAL 0x01
#define RPT_WRITE_MASK_VAL 0xFF
#define PER_WRITE_MASK_VAL 0xFFFFFFFF
#define PH1D_WRITE_MASK_VAL 0xFFFFFFFF

//READ_MASK_VAL
#define PID_READ_MASK_VAL 0x42071100
#define PCR_READ_MASK_VAL 0x01
#define CFG_READ_MASK_VAL 0x3007F
#define START_READ_MASK_VAL 0x01
#define RPT_READ_MASK_VAL 0xFF
#define PER_READ_MASK_VAL 0xFFFFFFFF
#define PH1D_READ_MASK_VAL 0xFFFFFFFF

//BIT_FIELDS_POS
#define PCR_FREE_BIT_POS 0
#define CFG_OPST_BIT_POS 17
#define CFG_CURLEV_BIT_POS 16
#define CFG_INTEN_BIT_POS 6
#define CFG_INACTOUT_BIT_POS 5
#define CFG_P1OUT_BIT_POS 4
#define CFG_EVTRIG_BIT_POS 2
#define CFG_MODE_BIT_POS 0
#define START_BIT_POS 0
#define RPT_BIT_POS 0
#define PER_BIT_POS 0
#define PH1D_BIT_POS 0

//BIT_FIELDS_MASK
#define PCR_FREE_BIT_MAKS_VAL 0x01
#define CFG_OPST_BIT_MAKS_VAL 0x01
#define CFG_CURLEV_BIT_MAKS_VAL 0x01
#define CFG_INTEN_BIT_MAKS_VAL 0x01
#define CFG_INACTOUT_BIT_MAKS_VAL 0x01
#define CFG_P1OUT_BIT__MAKS_VAL 0x01
#define CFG_EVTRIG_BIT_MAKS_VAL 0x03
#define CFG_MODE_BIT_MAKS_VAL 0x03
#define START_BIT_MAKS_VAL 0x01
#define RPT_BIT_MAKS_VAL 0xFF
#define PER_BIT_MAKS_VAL 0xFFFFFFFF
#define PH1D_BIT_MAKS_VAL 0xFFFFFFFF

enum pwm_state { DISABLE = 0, 
				 ONE_SHOT_MODE = 1, 
				 CONTINUOUS_MODE = 2
			   };
#endif 
